### ISSUE TITLE
Implement Dynamic Calendar

### ISSUE THREAD

**Issue by anlumo** [Metalab/metalab.at#1]
`index.html` should contain a list of the next 5 (7?) events that are relevant for externals from the calendar.

Right now this is hardcoded and only a placeholder.

**Comment by skauk** [comment]
Hi Andreas! It would be great to retain iCal export for the calendar to keep https://twitter.com/metalab_events running as well as ability to sync externally with Metalab events calendar. A nice bonus feature would be a way to get just future events.

**Comment by anlumo** [comment]
That's a different use case that could be handled by a different endpoint in MOS.

However, the bot would also benefit from only getting events that are relevant to externals.

**Comment by Hetti** [comment]
now I see what calls the iCal endpoint regularly :D @rcknr 

The iCal endpoint was improved and now only gives back last 7 days + future events due to high load of retrieving all events.
See PR: https://github.com/Metalab/mos/pull/119

**Comment by anlumo** [comment]
> now I see what calls the iCal endpoint regularly

I also have the Metalab calendar subscribed in my calendar app on three different machines.

**Comment by anlumo** [comment]
@rcknr can you modify the metalab_events bot to ignore events with `CLASS:PRIVATE`? This field was just deployed in https://github.com/Metalab/mos/pull/149

**Comment by skauk** [comment]
@anlumo Sure, I can. I see there are quite a few of private ones. What exactly does it stand for?

**Comment by anlumo** [comment]
> @anlumo Sure, I can. I see there are quite a few of private ones. What exactly does it stand for?

Some events are not interesting for people new to the space, like the Jour Fixe or the lounge cleanup day. We want to present a vetted list of events that new people might be interested in, so we can attract them to visit us. So, all external communication should use the vetted list (only public events).

**Comment by skauk** [comment]
Done. Only public events will be posted to Twitter from tomorrow on.

**Comment by anlumo** [comment]
> Done. Only public events will be posted to Twitter from tomorrow on.

Great, thank you!
