### ISSUE TITLE
Fix Map under Location tab

### ISSUE THREAD

**Issue by eest9** [Metalab/metalab.at#11]
The map in the location tap appears to be zoomed out at maximum. It should be zoomed in per default, like on the home page.

**Comment by boredoms** [comment]
This does not affect me, testing on Firefox 110.0 and Chrome 110.0.x.x. Can you please give some info on how to reproduce?

**Comment by boredoms** [comment]
It may happen if you scroll down and end up in map while scrolling if the map catches your cursor, could that be what happened?

**Comment by skauk** [comment]
This happens because embedded maps uses scroll events to zoom out. Home and Location pages appear to be using the same exact code to display the map.

**Comment by anlumo** [comment]
@eest9 what browser are you using?

**Comment by eest9** [comment]
Firefox, but the issue seems to be resolved
