### ISSUE TITLE
Door status on website

### ISSUE THREAD

**Issue by regendrogenbogen** [Metalab/metalab.at#14]
We have this nice door status: http://eingang.metalab.at/ 
It would be really great if it could be included on the website for visitors to see it directly

**Comment by anlumo** [comment]
REST API is at http://eingang.metalab.at/status.json

I can easily implement that, but I'd need to know where to place the information on the page and how it should look. We're already trying to unclutter the menu bar in #12, so adding something there is counter-productive.
