### ISSUE TITLE
Transfer Page to metalab.at

### ISSUE THREAD

**Issue by anlumo** [Metalab/metalab.at#4]
The page isn't live yet! This should change.

Additional work to be done:

- [x] Change link to Regulars Area to the new URL of the old page.
- [ ] Rework dome.metalab.at to use the new style and include the menu there.
- [x] #1
- [ ] #3

**Comment by boredoms** [comment]
Another possible task, if not too painful:

- [ ] Have the members area and MOS calendar use the same colors as the landing page and its subpages

**Comment by boredoms** [comment]
- [ ] Add Link to our Datenschutzerklärung in the footer of the page
- [ ] Either update the Datenschutzerklärung to include our use of OSM or change the map solution as to not require that

**Comment by skauk** [comment]
Can you please tell how's calendar going to work once you transition the website?

**Comment by anlumo** [comment]
> Can you please tell how's calendar going to work once you transition the website?

Look at the code [here](https://github.com/Metalab/metalab.at/blob/f3dd7bc588aab180c2cae74d3d94587e2bc62113/index.html#L273).

**Comment by skauk** [comment]
Okay, so the mos remains to run the calendar. I'm using this [URL](https://metalab.at/calendar/export/ical/) for @metalab_events and want to make sure it keeps working.

**Comment by anlumo** [comment]
Yes, there's no change there. The only thing I'm considering right now is to ask the backend team to add another calender endpoint that does not expose the private flag, because the handling of that is buggy in some calender clients.

However, this is in addition to the existing solution, so it doesn't change anything for the Twitter bot.

**Comment by skauk** [comment]
Thanks for clarification! If anything, please fill free to open an issue with [metalab/events_twitter](https://github.com/Metalab/events_twitter)

**Comment by anlumo** [comment]
Deployed!
