### ISSUE TITLE
Change Floorplan

### ISSUE THREAD

**Issue by anlumo** [Metalab/metalab.at#7]
The floorplan image is outdated, we need a new version of the current state (minus the piles of crap).

**Comment by boredoms** [comment]
New floorplan image was added in de40c5bfe865953470953891848b86b917872008

**Comment by boredoms** [comment]
depends on https://github.com/Metalab/metalab_floorplan/issues/3

**Comment by boredoms** [comment]
upstream is fixed, need to reimport and crop the floorplan

**Comment by boredoms** [comment]
imported from upstream in c72b10564961bcda9c023886292708582aabb728
