### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by anlumo** [Metalab/metalab.at#9]
Some people might be more comfortable with a German version of the page.

The default language should depend on the browser settings, but it should be possible to switch manually as well.

**Comment by boredoms** [comment]
Done as of d3b170bb5d2f5696dff354a158ebfd21e0e41fc5

**Comment by boredoms** [comment]
Translation is done as of d3b170bb5d2f5696dff354a158ebfd21e0e41fc5, needs a language select feature still.

**Comment by boredoms** [comment]
Language selection is implemented as of d3b170bb5d2f5696dff354a158ebfd21e0e41fc5, closing this issue
